version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pfe
    container_name: mydb
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=myapp:v1.0
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "8100:80"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306